# Generated by Django 3.0.3 on 2020-06-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('confirmed', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
            ],
        ),
    ]
